version: "3.7"

services:

  server:
    image: nginx:1.14.2-alpine
    restart: always
    volumes:
      - ./nginx/public_html:/public_html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./nginx/certbot/conf:/etc/nginx/ssl
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web_app
    links:
      - gateway

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email yanrus09@gmail.com --agree-tos --no-eff-email -d yaniddze.com
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/logs:/var/log/letsencrypt
      - ./nginx/certbot/data:/usr/share/nginx/html/letsencrypt

  web_app:
    build: ./web_app/
    volumes:
      - ./nginx/public_html:/app/build
    depends_on:
      - gateway
    links:
      - gateway

  gateway:
    build: ./AspGateway/AspGateway
    restart: always
    # ports:
    #   - "8088:80"
    depends_on:
      - identity-service 
    links:
      - identity-service

  postgres-identity:
    image: postgres:latest
    restart: always
    volumes:
      - ./database/someapi/data:/var/lib/postgresql/data
      - ./database/someapi/scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "money"
    
  identity-service:
    build: ./IdentityService/IdentityService
    restart: always
    depends_on:
      - "postgres-identity"
    # ports:
    #   - "8088:80"
    environment:
      DB_CONNECTION_STRING: "host=postgres-identity;port=5432;database=money;username=postgres;password=postgres"
